[SETTINGS]
# Basılacak tuş (shift, space, a, b, enter vb.)
key_to_press = shift
hold_duration = 60
wait_duration = 19

[CLICKER_1]
trigger_key = mouse4
target_key = q
delay = 10.5

[CLICKER_2]
trigger_key = mouse5
target_key = r
delay = 6.5

[RANDOM_CLICKER]
target_key = r
max_interval = 5.0